class ParticleEngine{
  constructor(canvas,getAnchor){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.getAnchor=getAnchor;this.items=[];this.config=null;this.running=true;this.last=performance.now();this.acc=0;this.resize();new ResizeObserver(()=>this.resize()).observe(canvas.parentElement);this.loop=this.loop.bind(this);requestAnimationFrame(this.loop)}
  resize(){const r=this.canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio,2);this.canvas.width=r.width*d;this.canvas.height=r.height*d;this.ctx.setTransform(d,0,0,d,0,0)}
  setConfig(config){if(this.config?.type!==config.type)this.items=[];this.config=config;if(!config.enabled)this.items=[]}
  spawn(burst=false){const c=burst?this.burstConfig:this.config;if(!c)return;const anchor=this.getAnchor(),amount=burst?c.count:1;for(let i=0;i<amount&&this.items.length<350;i++){const falling=['snow','rain','ash','leaves','petals','confetti'].includes(c.type),rising=['fire','embers','smoke'].includes(c.type);let angle=burst?Math.random()*Math.PI*2:((Math.random()-.5)*(c.spread||360)-90)*Math.PI/180;if(falling)angle=(75+Math.random()*30)*Math.PI/180;if(rising)angle=(-105+Math.random()*30)*Math.PI/180;const speed=(c.force||c.speed||25)*(.55+Math.random());let x=anchor.x,y=anchor.y;if(!burst&&c.area==='around'){x+=(Math.random()-.5)*anchor.width;y+=(Math.random()-.5)*anchor.height}if(!burst&&c.area==='top')y-=anchor.height/2;if(!burst&&c.area==='bottom')y+=anchor.height/2;if(falling){x+=(Math.random()-.5)*anchor.width;y-=anchor.height/2}this.items.push({x,y,vx:Math.cos(angle)*speed,vy:Math.sin(angle)*speed,size:(c.size||3)*(.6+Math.random()*.8),life:c.lifetime||1.5,max:c.lifetime||1.5,color:c.randomColor?`hsl(${Math.random()*360} 85% 70%)`:c.color||'#fff',type:burst?'sparkles':c.type,gravity:c.gravity||0,rotation:Math.random()*Math.PI*2,spin:(Math.random()-.5)*5,seed:Math.random()})}}
  burst(config){this.burstConfig={...config,type:config.type||'sparkles'};this.spawn(true)}
  draw(p,time,alpha){const ctx=this.ctx,s=p.size;ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.rotation);ctx.globalAlpha=alpha;ctx.fillStyle=p.color;ctx.strokeStyle=p.color;ctx.lineCap='round';switch(p.type){case'sparkles':case'magic':this.star(p.type==='magic'?5:4,s);break;case'snow':this.snowflake(s);break;case'rain':ctx.lineWidth=Math.max(1,s*.45);ctx.beginPath();ctx.moveTo(0,-s*2.6);ctx.lineTo(-s*.7,s*2.6);ctx.stroke();break;case'dust':ctx.globalAlpha=alpha*.55;ctx.beginPath();ctx.arc(0,0,s*.55,0,Math.PI*2);ctx.fill();break;case'ash':ctx.beginPath();ctx.moveTo(-s,0);ctx.quadraticCurveTo(0,-s*.7,s,0);ctx.quadraticCurveTo(0,s*.5,-s,0);ctx.fill();break;case'fog':case'smoke':{const gradient=ctx.createRadialGradient(0,0,0,0,0,s*3);gradient.addColorStop(0,p.color);gradient.addColorStop(1,'transparent');ctx.globalAlpha=alpha*(p.type==='fog'?.18:.32);ctx.fillStyle=gradient;ctx.beginPath();ctx.arc(0,0,s*3,0,Math.PI*2);ctx.fill();break}case'bubbles':ctx.globalAlpha=alpha*.75;ctx.lineWidth=Math.max(1,s*.25);ctx.beginPath();ctx.arc(0,0,s*1.45,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=alpha*.9;ctx.beginPath();ctx.arc(-s*.45,-s*.5,s*.22,0,Math.PI*2);ctx.fill();break;case'confetti':ctx.fillRect(-s*.65,-s*1.3,s*1.3,s*2.6);break;case'leaves':this.leaf(s);break;case'petals':this.petal(s);break;case'embers':ctx.shadowColor=p.color;ctx.shadowBlur=s*3;ctx.beginPath();ctx.ellipse(0,0,s*.45,s*1.7,0,0,Math.PI*2);ctx.fill();break;case'fire':this.flame(s);break;default:ctx.beginPath();ctx.arc(0,0,s,0,Math.PI*2);ctx.fill()}ctx.restore()}
  star(points,size){const ctx=this.ctx,outer=size*1.8,inner=size*.45;ctx.shadowColor=ctx.fillStyle;ctx.shadowBlur=size*2;ctx.beginPath();for(let i=0;i<points*2;i++){const radius=i%2?inner:outer,angle=-Math.PI/2+i*Math.PI/points,x=Math.cos(angle)*radius,y=Math.sin(angle)*radius;i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.closePath();ctx.fill()}
  snowflake(size){const ctx=this.ctx;ctx.lineWidth=Math.max(1,size*.28);for(let i=0;i<3;i++){ctx.rotate(Math.PI/3);ctx.beginPath();ctx.moveTo(-size*1.8,0);ctx.lineTo(size*1.8,0);ctx.moveTo(size*.8,0);ctx.lineTo(size*1.25,-size*.45);ctx.moveTo(size*.8,0);ctx.lineTo(size*1.25,size*.45);ctx.stroke()}}
  leaf(size){const ctx=this.ctx;ctx.beginPath();ctx.moveTo(-size*1.5,0);ctx.quadraticCurveTo(0,-size*1.5,size*1.6,0);ctx.quadraticCurveTo(0,size*1.2,-size*1.5,0);ctx.fill();ctx.globalAlpha*=.45;ctx.strokeStyle='#102b18';ctx.beginPath();ctx.moveTo(-size,0);ctx.lineTo(size,0);ctx.stroke()}
  petal(size){const ctx=this.ctx;ctx.beginPath();ctx.ellipse(0,0,size*.75,size*1.65,0,0,Math.PI*2);ctx.fill();ctx.globalAlpha*=.45;ctx.fillStyle='#fff';ctx.beginPath();ctx.ellipse(-size*.18,-size*.45,size*.16,size*.55,0,0,Math.PI*2);ctx.fill()}
  flame(size){const ctx=this.ctx;ctx.shadowColor=ctx.fillStyle;ctx.shadowBlur=size*2;ctx.beginPath();ctx.moveTo(0,-size*2.2);ctx.bezierCurveTo(size*1.5,-size*.5,size*1.3,size*1.4,0,size*1.8);ctx.bezierCurveTo(-size*1.3,size*1.4,-size*1.5,-size*.5,0,-size*2.2);ctx.fill();ctx.globalAlpha*=.65;ctx.fillStyle='#ffe56b';ctx.beginPath();ctx.moveTo(0,-size);ctx.quadraticCurveTo(size*.6,size*.5,0,size);ctx.quadraticCurveTo(-size*.6,size*.5,0,-size);ctx.fill()}
  loop(time){const dt=Math.min((time-this.last)/1000,.04);this.last=time;const c=this.config;if(this.running&&c?.enabled){this.acc+=dt*(Math.min(c.count,200)/Math.max(c.lifetime,.3));while(this.acc>=1){this.spawn();this.acc--}}this.ctx.clearRect(0,0,this.canvas.clientWidth,this.canvas.clientHeight);for(let i=this.items.length-1;i>=0;i--){const p=this.items[i];p.life-=dt;p.vy+=p.gravity*dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.rotation+=p.spin*dt;if(['leaves','petals','snow'].includes(p.type))p.x+=Math.sin(time/450+p.seed*10)*12*dt;if(p.life<=0){this.items.splice(i,1);continue}this.draw(p,time,Math.max(0,p.life/p.max)*(c?.opacity??1))}this.ctx.globalAlpha=1;requestAnimationFrame(this.loop)}
}
