const ANIMATIONS={float:{name:'Плавание',en:'Float',defaults:{amplitude:10,duration:2.5}},sway:{name:'Покачивание',en:'Sway',defaults:{amplitude:7,duration:2.8}},pulse:{name:'Пульсация',en:'Pulse',defaults:{amplitude:8,duration:1.8}},bounce:{name:'Прыжок',en:'Bounce',defaults:{amplitude:18,duration:1.2}},shake:{name:'Дрожание',en:'Shake',defaults:{amplitude:5,duration:.45}},rotate:{name:'Вращение',en:'Rotate',defaults:{amplitude:360,duration:4}},breathe:{name:'Дыхание',en:'Breathe',defaults:{amplitude:5,duration:3}},squash:{name:'Squash & Stretch',en:'Squash',defaults:{amplitude:10,duration:1.3}},blink:{name:'Мигание',en:'Blink',defaults:{amplitude:60,duration:1.5}},drift:{name:'Дрейф',en:'Drift',defaults:{amplitude:14,duration:4}}};
const EFFECTS={glow:{name:'Свечение',en:'Glow',defaults:{intensity:18,color:'#8b5cf6'}},neon:{name:'Неон',en:'Neon',defaults:{intensity:22,color:'#4de2e8'}},outline:{name:'Контур',en:'Outline',defaults:{intensity:3,color:'#ffffff'}},shadow:{name:'Тень',en:'Shadow',defaults:{intensity:15,color:'#000000'}},blur:{name:'Размытие',en:'Blur',defaults:{intensity:3,color:'#ffffff'}},tint:{name:'Окрашивание',en:'Tint',defaults:{intensity:30,color:'#9b71ff'}},grayscale:{name:'Чёрно-белый',en:'Grayscale',defaults:{intensity:100,color:'#ffffff'}},opacity:{name:'Прозрачность',en:'Opacity',defaults:{intensity:70,color:'#ffffff'}},flicker:{name:'Мерцание',en:'Flicker',defaults:{intensity:35,color:'#ffffff'}},flash:{name:'Вспышка',en:'Flash',defaults:{intensity:80,color:'#ffffff'}},glitch:{name:'Глитч',en:'Glitch',defaults:{intensity:7,color:'#ff3377'}},rgb:{name:'RGB-сдвиг',en:'RGB Shift',defaults:{intensity:6,color:'#33dfff'}},shimmer:{name:'Перелив',en:'Shimmer',defaults:{intensity:45,color:'#ffffff'}},hue:{name:'Смена оттенка',en:'Hue Shift',defaults:{intensity:90,color:'#ffffff'}}};
const PARTICLES={sparkles:{name:'Искры',icon:'✦',color:'#b99cff'},magic:{name:'Магия',icon:'◌',color:'#8b5cf6'},smoke:{name:'Дым',icon:'☁',color:'#98a0b2'},fire:{name:'Огонь',icon:'♨',color:'#ff7633'},snow:{name:'Снег',icon:'❄',color:'#d8f3ff'},dots:{name:'Точки',icon:'•',color:'#ffffff'}};
const BUILTIN_PRESETS=[
 {name:'Магический предмет',icon:'✨',animations:[['float',{amplitude:10,duration:2.5}]],effects:[['glow',{intensity:22,color:'#8b5cf6'}],['shimmer',{intensity:35,color:'#ffffff'}]],particles:{type:'sparkles',enabled:true,count:40,size:3,speed:28,color:'#b99cff'}},
 {name:'Призрак',icon:'👻',animations:[['float',{amplitude:7,duration:3.5}]],effects:[['opacity',{intensity:62}],['blur',{intensity:1}],['glow',{intensity:12,color:'#8adfff'}],['flicker',{intensity:20}]]},
 {name:'Заморозка',icon:'🧊',effects:[['glow',{intensity:18,color:'#79dfff'}],['hue',{intensity:180}]],particles:{type:'snow',enabled:true,count:35,size:3,speed:18,color:'#d8f3ff'}},
 {name:'Отравление',icon:'☠',animations:[['breathe',{amplitude:6,duration:2}]],effects:[['glow',{intensity:18,color:'#79ff62'}],['hue',{intensity:80}]]},
 {name:'Collectible',icon:'⭐',animations:[['float',{amplitude:9,duration:2}],['pulse',{amplitude:5,duration:1.5}]],effects:[['glow',{intensity:16,color:'#ffe66b'}]],particles:{type:'sparkles',enabled:true,count:25,size:2,speed:22,color:'#ffe66b'},hover:{scale:1.1,glow:20}},
 {name:'Огонь',icon:'🔥',animations:[['sway',{amplitude:4,duration:1.2}]],effects:[['glow',{intensity:22,color:'#ff5d28'}]],particles:{type:'fire',enabled:true,count:50,size:5,speed:35,color:'#ff7633'}},
 {name:'Электричество',icon:'⚡',animations:[['shake',{amplitude:2,duration:.2}]],effects:[['neon',{intensity:20,color:'#70cfff'}],['flicker',{intensity:25}]]},
 {name:'Получение урона',icon:'💥',effects:[['tint',{intensity:35,color:'#ff3030'}]],click:{bounce:true,flash:true,shake:true,burst:true}},
 {name:'Legendary Item',icon:'🌌',animations:[['float',{amplitude:12,duration:3}],['rotate',{amplitude:360,duration:10}]],effects:[['glow',{intensity:28,color:'#aa5cff'}],['shimmer',{intensity:55}]],particles:{type:'magic',enabled:true,count:60,size:4,speed:24,color:'#aa5cff'}},
 {name:'Glitch Object',icon:'📺',animations:[['shake',{amplitude:2,duration:.35}]],effects:[['glitch',{intensity:8}],['rgb',{intensity:5}],['flicker',{intensity:25}]]}
];
const defaultConfig=()=>({version:1,name:'Новый игровой ассет',asset:null,transform:{x:0,y:0,scale:1,rotation:0},animations:[],effects:[],particles:{enabled:false,type:'sparkles',count:35,size:3,speed:25,spread:360,lifetime:1.8,gravity:0,opacity:.85,color:'#b99cff',randomColor:false,area:'around'},interactions:{hover:{scale:1,glow:0,brightness:100,rotate:0,shake:false,pulse:false},click:{bounce:true,squash:false,flash:false,shake:false,burst:true},burst:{count:30,force:90,size:4,lifetime:.8,color:'#d7c8ff'}}});
