const ANIMATIONS={float:{name:'Плавание',en:'Float',defaults:{amplitude:10,duration:2.5}},sway:{name:'Покачивание',en:'Sway',defaults:{amplitude:7,duration:2.8}},pulse:{name:'Пульсация',en:'Pulse',defaults:{amplitude:8,duration:1.8}},bounce:{name:'Прыжок',en:'Bounce',defaults:{amplitude:18,duration:1.2}},shake:{name:'Дрожание',en:'Shake',defaults:{amplitude:5,duration:.45}},rotate:{name:'Вращение',en:'Rotate',defaults:{amplitude:360,duration:4}},breathe:{name:'Дыхание',en:'Breathe',defaults:{amplitude:5,duration:3}},squash:{name:'Squash & Stretch',en:'Squash',defaults:{amplitude:10,duration:1.3}},blink:{name:'Мигание',en:'Blink',defaults:{amplitude:60,duration:1.5}},drift:{name:'Дрейф',en:'Drift',defaults:{amplitude:14,duration:4}}};
const EFFECTS={glow:{name:'Свечение',en:'Glow',defaults:{intensity:18,color:'#8b5cf6'}},neon:{name:'Неон',en:'Neon',defaults:{intensity:22,color:'#4de2e8'}},outline:{name:'Контур',en:'Outline',defaults:{intensity:3,color:'#ffffff'}},shadow:{name:'Тень',en:'Shadow',defaults:{intensity:15,color:'#000000'}},blur:{name:'Размытие',en:'Blur',defaults:{intensity:3,color:'#ffffff'}},tint:{name:'Окрашивание',en:'Tint',defaults:{intensity:30,color:'#9b71ff'}},grayscale:{name:'Чёрно-белый',en:'Grayscale',defaults:{intensity:100,color:'#ffffff'}},opacity:{name:'Прозрачность',en:'Opacity',defaults:{intensity:70,color:'#ffffff'}},flicker:{name:'Мерцание',en:'Flicker',defaults:{intensity:35,color:'#ffffff'}},flash:{name:'Вспышка',en:'Flash',defaults:{intensity:80,color:'#ffffff'}},glitch:{name:'Глитч',en:'Glitch',defaults:{intensity:7,color:'#ff3377'}},rgb:{name:'RGB-сдвиг',en:'RGB Shift',defaults:{intensity:6,color:'#33dfff'}},shimmer:{name:'Перелив',en:'Shimmer',defaults:{intensity:45,color:'#ffffff'}},hue:{name:'Смена оттенка',en:'Hue Shift',defaults:{intensity:90,color:'#ffffff'}}};
const PARTICLES={sparkles:{name:'Искры',icon:'✦',color:'#b99cff'},magic:{name:'Магия',icon:'◌',color:'#8b5cf6'},smoke:{name:'Дым',icon:'☁',color:'#98a0b2'},fire:{name:'Огонь',icon:'♨',color:'#ff7633'},snow:{name:'Снег',icon:'❄',color:'#d8f3ff'},dots:{name:'Точки',icon:'•',color:'#ffffff'}};
const BUILTIN_PRESETS=[
 {name:'Магический предмет',icon:'✨',animations:[['float',{amplitude:10,duration:2.5}]],effects:[['glow',{intensity:22,color:'#8b5cf6'}],['shimmer',{intensity:35,color:'#ffffff'}]],particles:{type:'sparkles',enabled:true,count:40,size:3,speed:28,color:'#b99cff'}},
 {name:'Призрак',icon:'👻',animations:[['float',{amplitude:7,duration:3.5}]],effects:[['opacity',{intensity:62}],['blur',{intensity:1}],['glow',{intensity:12,color:'#8adfff'}],['flicker',{intensity:20}]]},
 {name:'Заморозка',icon:'🧊',effects:[['glow',{intensity:18,color:'#79dfff'}],['hue',{intensity:180}]],particles:{type:'snow',enabled:true,count:35,size:3,speed:18,color:'#d8f3ff'}},
 {name:'Отравление',icon:'☠',animations:[['breathe',{amplitude:6,duration:2}]],effects:[['glow',{intensity:18,color:'#79ff62'}],['hue',{intensity:80}]]},
 {name:'Collectible',icon:'⭐',animations:[['float',{amplitude:9,duration:2}],['pulse',{amplitude:5,duration:1.5}]],effects:[['glow',{intensity:16,color:'#ffe66b'}]],particles:{type:'sparkles',enabled:true,count:25,size:2,speed:22,color:'#ffe66b'},hover:{scale:1.1,glow:20}},
 {name:'Огонь',icon:'🔥',animations:[['sway',{amplitude:4,duration:1.2}]],effects:[['glow',{intensity:22,color:'#ff5d28'}]],particles:{type:'fire',enabled:true,count:50,size:5,speed:35,color:'#ff7633'}},
 {name:'Электричество',icon:'⚡',animations:[['shake',{amplitude:2,duration:.2}]],effects:[['neon',{intensity:20,color:'#70cfff'}],['flicker',{intensity:25}]]},
 {name:'Получение урона',icon:'💥',effects:[['tint',{intensity:35,color:'#ff3030'}]],click:{bounce:true,flash:true,shake:true,burst:true}},
 {name:'Legendary Item',icon:'🌌',animations:[['float',{amplitude:12,duration:3}],['rotate',{amplitude:360,duration:10}]],effects:[['glow',{intensity:28,color:'#aa5cff'}],['shimmer',{intensity:55}]],particles:{type:'magic',enabled:true,count:60,size:4,speed:24,color:'#aa5cff'}},
 {name:'Glitch Object',icon:'📺',animations:[['shake',{amplitude:2,duration:.35}]],effects:[['glitch',{intensity:8}],['rgb',{intensity:5}],['flicker',{intensity:25}]]}
];
const defaultConfig=()=>({version:1,name:'Новый игровой ассет',asset:null,transform:{x:0,y:0,scale:1,rotation:0},animations:[],effects:[],particles:{enabled:false,type:'sparkles',count:35,size:3,speed:25,spread:360,lifetime:1.8,gravity:0,opacity:.85,color:'#b99cff',randomColor:false,area:'around'},interactions:{hover:{scale:1,glow:0,brightness:100,rotate:0,shake:false,pulse:false},click:{bounce:true,squash:false,flash:false,shake:false,burst:true},burst:{count:30,force:90,size:4,lifetime:.8,color:'#d7c8ff'}}});

// Схемы параметров используются и редактором, и движком эффектов.
const EFFECT_CONTROLS={
 glow:{radius:{label:'Радиус',min:0,max:60,step:1,unit:' px',value:18},strength:{label:'Сила',min:0,max:100,step:1,unit:'%',value:70},color:{label:'Цвет',type:'color',value:'#8b5cf6'},pulse:{label:'Пульсация',type:'toggle',value:false}},
 neon:{radius:{label:'Радиус',min:0,max:60,step:1,unit:' px',value:22},strength:{label:'Сила',min:0,max:100,step:1,unit:'%',value:80},color:{label:'Цвет',type:'color',value:'#4de2e8'}},
 outline:{width:{label:'Толщина',min:1,max:12,step:1,unit:' px',value:2},color:{label:'Цвет',type:'color',value:'#ffffff'}},
 shadow:{x:{label:'Смещение X',min:-50,max:50,step:1,unit:' px',value:8},y:{label:'Смещение Y',min:-50,max:50,step:1,unit:' px',value:12},blur:{label:'Размытие',min:0,max:60,step:1,unit:' px',value:18},opacity:{label:'Прозрачность',min:0,max:100,step:1,unit:'%',value:55},color:{label:'Цвет',type:'color',value:'#000000'}},
 blur:{radius:{label:'Размытие',min:0,max:20,step:.5,unit:' px',value:3}},
 tint:{amount:{label:'Насыщенность цвета',min:0,max:100,step:1,unit:'%',value:35},color:{label:'Цвет',type:'color',value:'#9b71ff'}},
 grayscale:{amount:{label:'Интенсивность',min:0,max:100,step:1,unit:'%',value:100}},opacity:{amount:{label:'Прозрачность',min:0,max:100,step:1,unit:'%',value:70}},
 flicker:{frequency:{label:'Частота',min:1,max:20,step:.5,unit:' Гц',value:7},randomness:{label:'Случайность',min:0,max:100,step:1,unit:'%',value:55},minOpacity:{label:'Мин. прозрачность',min:5,max:100,step:1,unit:'%',value:45}},
 flash:{frequency:{label:'Частота',min:.2,max:5,step:.1,unit:' Гц',value:1},brightness:{label:'Яркость',min:100,max:400,step:5,unit:'%',value:220},color:{label:'Цвет вспышки',type:'color',value:'#ffffff'}},
 glitch:{strength:{label:'Сила',min:0,max:30,step:1,unit:' px',value:7},frequency:{label:'Частота',min:1,max:20,step:.5,unit:' Гц',value:8},rgbDistance:{label:'RGB-сдвиг',min:0,max:30,step:1,unit:' px',value:6},slices:{label:'Количество срезов',min:1,max:12,step:1,unit:'',value:5}},
 rgb:{distance:{label:'Расстояние RGB',min:0,max:30,step:1,unit:' px',value:6},angle:{label:'Угол',min:0,max:360,step:1,unit:'°',value:0}},
 shimmer:{angle:{label:'Угол',min:0,max:360,step:1,unit:'°',value:25},width:{label:'Ширина блика',min:5,max:70,step:1,unit:'%',value:24},speed:{label:'Скорость',min:.3,max:6,step:.1,unit:' c',value:1.8},brightness:{label:'Яркость',min:100,max:350,step:5,unit:'%',value:190}},
 hue:{angle:{label:'Угол оттенка',min:0,max:360,step:1,unit:'°',value:90},animate:{label:'Анимировать',type:'toggle',value:false},speed:{label:'Скорость',min:.5,max:10,step:.1,unit:' c',value:4}}
};
Object.entries(EFFECTS).forEach(([type,effect])=>{const schema=EFFECT_CONTROLS[type];if(schema)effect.defaults=Object.fromEntries(Object.entries(schema).map(([key,field])=>[key,field.value]))});
