/* Stage 2 enhancements. Kept separate so the core editor remains readable. */
(function(){
  var deepCopy=value=>JSON.parse(JSON.stringify(value));
  var effectExpanded=0,snapGrid=false,snapCenter=true,snapshots={A:null,B:null},history=[],historyIndex=-1,historyLock=false;

  function normalizeEffects(){config.effects=config.effects.filter(effect=>EFFECTS[effect.type]);config.effects.forEach(effect=>{var schema=EFFECT_CONTROLS[effect.type]||{};var next={};Object.entries(schema).forEach(([key,field])=>{var value=effect.params?.[key]??field.value;if(field.type!=='color'&&field.type!=='toggle'){value=Number(value);if(!Number.isFinite(value))value=field.value;value=Math.max(field.min,Math.min(field.max,value))}next[key]=value});effect.params=next;effect.enabled=effect.enabled!==false;effect.solo=!!effect.solo})}
  normalizeEffects();

  var originalChanged=changed;
  function projectSnapshot(){var copy=deepCopy(config);if(copy.asset)copy.asset.url=null;return copy}
  function pushHistory(){if(historyLock)return;var next=JSON.stringify(projectSnapshot());if(history[historyIndex]===next)return;history=history.slice(0,historyIndex+1);history.push(next);if(history.length>60)history.shift();historyIndex=history.length-1;updateHistoryButtons()}
  changed=function(){normalizeEffects();originalChanged();pushHistory();updateCoordinates()};
  function restoreHistory(index){if(index<0||index>=history.length)return;historyLock=true;var asset=config.asset;config={...defaultConfig(),...JSON.parse(history[index]),asset};normalizeEffects();renderEditor();renderPreview();persist();updateCounts();historyLock=false;historyIndex=index;updateHistoryButtons();toast(index===history.length-1?'Изменения возвращены':'Изменение отменено')}
  function updateHistoryButtons(){$('#undoBtn').disabled=historyIndex<=0;$('#redoBtn').disabled=historyIndex>=history.length-1;$('#undoBtn').style.opacity=$('#undoBtn').disabled?'.35':'1';$('#redoBtn').style.opacity=$('#redoBtn').disabled?'.35':'1'}
  pushHistory();$('#undoBtn').onclick=()=>restoreHistory(historyIndex-1);$('#redoBtn').onclick=()=>restoreHistory(historyIndex+1);

  var originalRenderEffects=renderEffects;
  function previewIcon(type){return`<span class="stack-preview preview-${type}"><i class="mini-crystal"></i></span>`}
  function effectField(effect,index,key,field){var value=effect.params[key]??field.value;if(field.type==='color')return`<div class="control"><label>${field.label}</label><input type="color" data-color="effect" data-index="${index}" data-param="${key}" value="${value}"></div>`;if(field.type==='toggle')return`<div class="control"><label><span>${field.label}</span><input class="toggle" type="checkbox" data-effect-toggle="${index}:${key}" ${value?'checked':''}></label></div>`;return control(field.label,key,value,field.min,field.max,field.step,`effect:${index}`,field.unit||'')}
  renderEffects=function(){normalizeEffects();var stack=config.effects.map((effect,index)=>{var meta=EFFECTS[effect.type],schema=EFFECT_CONTROLS[effect.type]||{};return`<div class="stack-item" draggable="true" data-stack-index="${index}"><div class="stack-head" data-expand-effect="${index}"><span class="stack-grip" title="Перетащить">⋮⋮</span>${previewIcon(effect.type)}<span class="stack-name"><strong>${meta.name}</strong><small>${meta.en}</small></span><button class="stack-action ${effect.enabled?'active':''}" data-eye-effect="${index}" title="Показать/скрыть">◉</button><button class="stack-action ${effect.solo?'active':''}" data-solo-effect="${index}" title="Только этот эффект">S</button><button class="stack-action" data-duplicate-effect="${index}" title="Дублировать">⧉</button><button class="stack-action" data-remove="effect" data-index="${index}" title="Удалить">×</button></div>${effectExpanded===index?`<div class="stack-params">${Object.entries(schema).map(([key,field])=>effectField(effect,index,key,field)).join('')}<button class="btn compact" data-random-effect="${index}">🎲 Вариация</button></div>`:''}</div>`}).join('');editor.innerHTML=`<p class="section-note">Перетащите эффекты, чтобы изменить порядок. S изолирует один эффект.</p><div class="effect-stack">${stack||'<div class="empty-editor">Добавьте первый эффект</div>'}</div><div class="add-title">ДОБАВИТЬ ЭФФЕКТ</div><div class="picker-grid effect-picker">${Object.entries(EFFECTS).map(([type,meta])=>`<button class="picker-card" data-add-effect="${type}">${previewIcon(type)}<span><strong>${meta.name}</strong><small>${meta.en}</small></span></button>`).join('')}</div>`}
  var baseBindEditor=bindEditor;
  bindEditor=function(){baseBindEditor();editor.querySelectorAll('[data-param]').forEach(input=>input.oninput=()=>{config.effects[input.dataset.index].params[input.dataset.param]=input.value;changed()});editor.querySelectorAll('[data-expand-effect]').forEach(head=>head.onclick=()=>{effectExpanded=effectExpanded===+head.dataset.expandEffect?-1:+head.dataset.expandEffect;renderEditor()});editor.querySelectorAll('[data-eye-effect]').forEach(button=>button.onclick=event=>{event.stopPropagation();var effect=config.effects[button.dataset.eyeEffect];effect.enabled=!effect.enabled;renderEditor();changed()});editor.querySelectorAll('[data-solo-effect]').forEach(button=>button.onclick=event=>{event.stopPropagation();var index=+button.dataset.soloEffect,on=!config.effects[index].solo;config.effects.forEach(effect=>effect.solo=false);config.effects[index].solo=on;renderEditor();changed()});editor.querySelectorAll('[data-duplicate-effect]').forEach(button=>button.onclick=event=>{event.stopPropagation();var index=+button.dataset.duplicateEffect;config.effects.splice(index+1,0,deepCopy(config.effects[index]));effectExpanded=index+1;renderEditor();changed()});editor.querySelectorAll('[data-effect-toggle]').forEach(input=>input.onchange=()=>{var [index,key]=input.dataset.effectToggle.split(':');config.effects[index].params[key]=input.checked;changed()});editor.querySelectorAll('[data-random-effect]').forEach(button=>button.onclick=()=>randomizeEffect(+button.dataset.randomEffect));var dragged=null;editor.querySelectorAll('[data-stack-index]').forEach(item=>{item.ondragstart=()=>{dragged=+item.dataset.stackIndex;item.classList.add('dragging')};item.ondragend=()=>item.classList.remove('dragging');item.ondragover=e=>e.preventDefault();item.ondrop=e=>{e.preventDefault();var target=+item.dataset.stackIndex;if(dragged===target)return;var [moving]=config.effects.splice(dragged,1);config.effects.splice(target,0,moving);effectExpanded=target;renderEditor();changed()}})}
  function randomizeEffect(index){var effect=config.effects[index],schema=EFFECT_CONTROLS[effect.type];Object.entries(schema).forEach(([key,field])=>{if(field.type==='color'){var palette=['#8b5cf6','#4de2e8','#ff5f9e','#79e889','#ffd166'];effect.params[key]=palette[Math.floor(Math.random()*palette.length)]}else if(field.type!=='toggle'){var low=field.min+(field.max-field.min)*.2,high=field.min+(field.max-field.min)*.75,value=low+Math.random()*(high-low);effect.params[key]=field.step>=1?Math.round(value):Math.round(value/field.step)*field.step}});renderEditor();changed();toast('Создана безопасная вариация')}

  var originalRenderInteractions=renderInteractions;
  renderInteractions=function(){originalRenderInteractions();var first=editor.querySelector('.editor-block .controls');if(first)first.insertAdjacentHTML('beforeend',`${control('Усиление свечения','glow',config.interactions.hover.glow,0,50,1,'hover',' px')}<div class="picker-grid">${checks('hover',config.interactions.hover,[['shake','Дрожание'],['pulse','Пульсация']])}</div>`)}

  var originalRenderPresets=renderPresets;
  renderPresets=function(){var mine=JSON.parse(localStorage.getItem('gal-presets')||'[]');editor.innerHTML=`<p class="section-note">Сначала посмотрите комбинацию, затем примените её к проекту.</p><div class="preset-grid">${BUILTIN_PRESETS.map((preset,index)=>{var tags=[...(preset.animations||[]).map(x=>ANIMATIONS[x[0]].en),...(preset.effects||[]).slice(0,2).map(x=>EFFECTS[x[0]].en),preset.particles?PARTICLES[preset.particles.type].name:null].filter(Boolean).join(' · ');return`<article class="preset-card large"><div class="preset-demo" style="--preset-color:${preset.effects?.[0]?.[1]?.color||'#8b5cf6'}"><i class="mini-crystal"></i></div><strong>${preset.icon} ${preset.name}</strong><small>${tags}</small><div class="preset-actions"><button data-preset="${index}">Применить</button><button data-preview-preset="${index}">Предпросмотр</button></div></article>`}).join('')}</div><div class="add-title">МОИ ПРЕСЕТЫ</div>${mine.length?`<div class="preset-grid">${mine.map((preset,index)=>`<button class="preset-card" data-my-preset="${index}"><strong>◇ ${preset.name}</strong></button>`).join('')}</div>`:'<div class="empty-editor">Здесь появятся ваши пресеты</div>'}<br><button class="btn compact" data-action="import">Импорт .JSON</button> <button class="btn compact" data-action="preset-json">Экспорт JSON</button>`;editor.querySelectorAll('[data-preview-preset]').forEach(button=>button.onclick=()=>previewPreset(+button.dataset.previewPreset))}
  function previewPreset(index){var before=projectSnapshot(),asset=config.asset;applyPreset(BUILTIN_PRESETS[index]);toast('Предпросмотр — настройки вернутся через 2 секунды');setTimeout(()=>{historyLock=true;config={...defaultConfig(),...before,asset};normalizeEffects();renderEditor();renderPreview();historyLock=false},2000)}

  function addStageTools(){stage.insertAdjacentHTML('afterbegin','<div class="work-area"></div><div class="stage-tools"><button id="originalBtn" title="Удерживайте для просмотра исходника">◉ Original</button><button id="fitBtn">Fit</button><button id="snapCenterBtn" class="active">⌖ Center</button><button id="snapGridBtn"># Grid</button></div>');root.classList.add('selected');root.insertAdjacentHTML('beforeend','<span class="coordinates" id="assetCoordinates">X 0 · Y 0</span>');var original=$('#originalBtn');var showOriginal=()=>{applyEffects(root,{...config,effects:[]});applyAnimations(root,{...config,animations:[]},true);particles.running=false;original.classList.add('active')};var showResult=()=>{renderPreview();particles.running=true;original.classList.remove('active')};original.onpointerdown=showOriginal;original.onpointerup=showResult;original.onpointerleave=showResult;$('#fitBtn').onclick=()=>{config.transform.x=0;config.transform.y=0;config.transform.scale=Math.min(1,(stage.clientWidth*.55)/(config.asset?.width||300),(stage.clientHeight*.55)/(config.asset?.height||300));renderEditor();changed()};$('#snapCenterBtn').onclick=()=>{snapCenter=!snapCenter;$('#snapCenterBtn').classList.toggle('active',snapCenter)};$('#snapGridBtn').onclick=()=>{snapGrid=!snapGrid;$('#snapGridBtn').classList.toggle('active',snapGrid)};root.addEventListener('pointerup',()=>{if(snapCenter){if(Math.abs(config.transform.x)<18)config.transform.x=0;if(Math.abs(config.transform.y)<18)config.transform.y=0}if(snapGrid){config.transform.x=Math.round(config.transform.x/10)*10;config.transform.y=Math.round(config.transform.y/10)*10}renderPreview();updateCoordinates()});updateCoordinates()}
  function updateCoordinates(){var node=$('#assetCoordinates');if(node)node.textContent=`X ${Math.round(config.transform.x)} · Y ${Math.round(config.transform.y)}`}
  addStageTools();

  function addSnapshots(){var footer=document.querySelector('.right-panel>footer');footer.insertAdjacentHTML('beforebegin','<div class="snapshot-bar"><button data-snapshot="A">A · сохранить</button><button data-snapshot="B">B · сохранить</button></div>');document.querySelectorAll('[data-snapshot]').forEach(button=>button.onclick=event=>{var key=button.dataset.snapshot;if(!snapshots[key]||event.shiftKey){snapshots[key]=projectSnapshot();button.textContent=`${key} · снимок`;toast(`Snapshot ${key} сохранён`);return}var asset=config.asset;historyLock=true;config={...defaultConfig(),...deepCopy(snapshots[key]),asset};normalizeEffects();renderEditor();renderPreview();historyLock=false;document.querySelectorAll('[data-snapshot]').forEach(x=>x.classList.toggle('active',x===button));toast(`Показан Snapshot ${key}`)})}
  addSnapshots();

  function labDialog(title,content,buttons){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=`<div class="modal-content lab-dialog">${content}<div class="modal-actions">${buttons.map((button,index)=>`<button class="btn ${button.primary?'primary':''}" data-dialog-button="${index}">${button.label}</button>`).join('')}</div></div>`;$('#modalBackdrop').classList.remove('hidden');buttons.forEach((button,index)=>$(`[data-dialog-button="${index}"]`).onclick=()=>button.action())}
  function closeLabDialog(){$('#modalBackdrop').classList.add('hidden')}
  savePreset=function(){labDialog('Сохранить пресет','<div class="control"><label>Название пресета</label><input id="presetNameInput" type="text" placeholder="Например, Ледяная реликвия" autofocus></div>',[{label:'Отмена',action:closeLabDialog},{label:'Сохранить',primary:true,action:()=>{var name=$('#presetNameInput').value.trim();if(!name){toast('Введите название',true);return}var mine=JSON.parse(localStorage.getItem('gal-presets')||'[]');mine.push({name,config:{...projectSnapshot(),asset:null}});localStorage.setItem('gal-presets',JSON.stringify(mine));closeLabDialog();toast('Пресет сохранён');if(section==='presets')renderEditor()}}])};$('#savePresetBtn').onclick=savePreset;
  function importDialog(){labDialog('Импорт пресета','<input id="jsonFileInput" type="file" accept="application/json,.json" hidden><div class="drop-json" id="jsonDrop">Перетащите .json сюда<br><br><button class="btn compact" id="chooseJson">Выбрать файл</button></div><p class="section-note">Будут приняты только корректные пресеты GAME ASSET LAB.</p>',[{label:'Закрыть',action:closeLabDialog}]);var input=$('#jsonFileInput'),drop=$('#jsonDrop');$('#chooseJson').onclick=()=>input.click();input.onchange=()=>input.files[0]&&readPresetFile(input.files[0]);drop.ondragover=e=>{e.preventDefault();drop.classList.add('dragover')};drop.ondragleave=()=>drop.classList.remove('dragover');drop.ondrop=e=>{e.preventDefault();drop.classList.remove('dragover');e.dataTransfer.files[0]&&readPresetFile(e.dataTransfer.files[0])}}
  function validPreset(parsed){return parsed&&Array.isArray(parsed.animations)&&Array.isArray(parsed.effects)&&parsed.animations.every(item=>ANIMATIONS[item.type])&&parsed.effects.every(item=>EFFECTS[item.type])&&(!parsed.particles||PARTICLES[parsed.particles.type])}
  async function readPresetFile(file){try{if(!file.name.toLowerCase().endsWith('.json')||file.size>2*1024*1024)throw Error();var parsed=JSON.parse(await file.text());if(!validPreset(parsed))throw Error();var asset=config.asset;config={...defaultConfig(),...parsed,asset};normalizeEffects();closeLabDialog();renderEditor();changed();toast('Пресет импортирован')}catch{toast('Файл не является корректным пресетом',true)}}
  var baseAction=action;action=function(name){if(name==='import')return importDialog();return baseAction(name)};
  $('#resetProject').onclick=()=>labDialog('Сбросить весь проект?','<p>Будут удалены настройки, эффекты, частицы и сохранённое локально изображение. Это действие нельзя отменить.</p>',[{label:'Отмена',action:closeLabDialog},{label:'Сбросить',primary:true,action:()=>{config=defaultConfig();removeAsset();renderEditor();changed();assetStoreDelete();closeLabDialog();toast('Проект сброшен')}}]);

  // IndexedDB stores the original Blob without inflating localStorage.
  function assetDb(){return new Promise((resolve,reject)=>{var request=indexedDB.open('game-asset-lab',1);request.onupgradeneeded=()=>request.result.createObjectStore('assets');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
  async function assetStorePut(file){try{var db=await assetDb(),tx=db.transaction('assets','readwrite');tx.objectStore('assets').put(file,'current');await new Promise((resolve,reject)=>{tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});db.close()}catch{toast('Браузер не разрешил сохранить изображение локально',true)}}
  async function assetStoreDelete(){try{var db=await assetDb(),tx=db.transaction('assets','readwrite');tx.objectStore('assets').delete('current');db.close()}catch{}}
  async function restoreAssetBlob(){if(window.GAL_SCENE_V3)return;try{var db=await assetDb(),tx=db.transaction('assets','readonly'),request=tx.objectStore('assets').get('current');request.onsuccess=async()=>{if(request.result&&!assetUrl){var savedTransform={...config.transform};setAsset(await loadAsset(request.result));config.transform=savedTransform;renderPreview();persist();updateCoordinates();toast('Ассет восстановлен из локального хранилища')}db.close()}}catch{}}
  takeFile=async function(file){try{setAsset(await loadAsset(file));await assetStorePut(file)}catch(error){toast(error.message||'Не удалось загрузить изображение',true)}};restoreAssetBlob();

  // Real FPS meter, averaged to avoid noisy digits.
  var fpsFrames=0,fpsLast=performance.now();function fpsLoop(now){fpsFrames++;if(now-fpsLast>=500){$('#fps').textContent=`${Math.round(fpsFrames*1000/(now-fpsLast))} FPS`;fpsFrames=0;fpsLast=now}requestAnimationFrame(fpsLoop)}requestAnimationFrame(fpsLoop);

  // Re-render with the enhanced editors and section identity.
  var baseRenderEditor=renderEditor;renderEditor=function(){document.body.className=`section-${section}`;baseRenderEditor()};renderEditor();renderPreview();updateCoordinates();
})();
